name: "Chromatic Deployment"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change to client directory
        run: cd client
      - name: Install dependencies
        run: yarn
      - name: Install Chromatic
        run: yarn add chromatic@6.24.1
      - name: Run Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        env:
          PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
