name: 'Chromatic Deployment'

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies in client directory
        run: npm install --prefix client
      - name: Install Chromatic
        run: npm install --prefix client chromatic@6.24.1
      - name: Install cli-table module
        run: npm install --prefix client cli-table
      - name: Run Chromatic
        run: bash -c 'cd client && npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}'
        env:
          PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
