name: "Chromatic Deployment"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change to client directory
        run: cd client
      - name: Install dependencies
        run: yarn
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.PRIVATE_TOKEN }}
