name: "Chromatic Deployment"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Change to client directory
        run: cd client  # 루트에서 client 폴더로 이동
      - name: Install dependencies
        run: npm install  # npm을 사용하여 종속성 설치
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.PRIVATE_TOKEN }}
